# -*- coding: utf-8 -*-
"""vetores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsMU3oQnZC2fgq8fXmU0R-vMUPSaEoNj
"""

#ExB
#Num programa Python, crie um array com os seguintes valores "iesp”, "2020.1”, "SI”, "ED”. Em seguida, imprima apenas o segundo valor do array (é o valor 2020.1).
def main():
    vetor = ["IESP", "2020.1", "SI", "ED"]
    print(vetor[1])

main()